// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAok1q1o25nEyQUe5LCnvE5gL2j5RgaJk',
    appId: '1:750458988224:web:1ff3e786884ea11ee26f25',
    messagingSenderId: '750458988224',
    projectId: 'projeto-epp',
    authDomain: 'projeto-epp.firebaseapp.com',
    storageBucket: 'projeto-epp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-jiD02IVSbCq2HP-I91XBXfKpwRgtl4',
    appId: '1:750458988224:android:53375cc4e06b89e2e26f25',
    messagingSenderId: '750458988224',
    projectId: 'projeto-epp',
    storageBucket: 'projeto-epp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DCImSrzDhEUf-rha-kY7Cm4XOnp9vS8',
    appId: '1:750458988224:ios:b75455e2b8856208e26f25',
    messagingSenderId: '750458988224',
    projectId: 'projeto-epp',
    storageBucket: 'projeto-epp.appspot.com',
    iosClientId: '750458988224-8brlo2g348tb28vrjbcld5iollb1sj4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.eppDemo',
  );
}
